### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by eli-schwartz** [kovidgoyal/rapydscript-ng#125]
Similar story to #67 

Building rapydscript-ng from scratch fails with the following errors:

```
Failed running: /tmp/generators.pyj-es5.js
generators.pyj:
/tmp/generators.pyj-es5.js:8
    == Op &&
    ^^

SyntaxError: Unexpected token ==
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInNewContext (vm.js:312:10)
    at /build/rapydscript-ng-git/src/rapydscript-ng/tools/test.js:78:20
    at Array.forEach (<anonymous>)
    at module.exports (/build/rapydscript-ng-git/src/rapydscript-ng/tools/test.js:45:11)
    at Object.<anonymous> (/build/rapydscript-ng-git/src/rapydscript-ng/bin/rapydscript:48:21)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)


generators.pyj:	test failed

[...]

Failed running: /tmp/repl.pyj-es5.js
repl.pyj:
baselib-plain-pretty.js:6
== Op &&
^^

SyntaxError: Unexpected token ==
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInContext (vm.js:300:10)
    at create_ctx (/build/rapydscript-ng-git/src/rapydscript-ng/tools/repl.js:21:5)
    at module.exports (/build/rapydscript-ng-git/src/rapydscript-ng/tools/repl.js:78:12)
    at /tmp/repl.pyj-es5.js:3889:9
    at /tmp/repl.pyj-es5.js:3944:7
    at /tmp/repl.pyj-es5.js:3945:3
    at Script.runInContext (vm.js:133:20)
    at Script.runInNewContext (vm.js:139:17)


repl.pyj:	test failed

[...]

There were 2 test failure(s):
generators.pyj repl.pyj
```

Note that it initially worked fine when building from an old source tree, but when rebuilding in a clean chroot, the tests started failing. Some changing npm dependency perhaps?

**Comment by eli-schwartz** [comment]
Thanks for the prompt fix!
