### ISSUE TITLE
Help: compiler not working

### ISSUE THREAD

**Issue by mardon86** [kovidgoyal/rapydscript-ng#18]
[mardon86@archlinux bin]$ ./rapydscript
module.js:341
    throw err;
    ^

Error: Cannot find module 'regenerator'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/media/DATA/GITs/rapydscript-ng/tools/compiler.js:16:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

fresh clone from git
node-5.10.0

**Comment by kovidgoyal** [comment]
That looks like you forgot to run npm install

See the installation instructions.
