### ISSUE TITLE
Buidling in-browser compiler

### ISSUE THREAD

**Issue by BruceSherwood** [kovidgoyal/rapydscript-ng#27]
I just updated rapydscript-ng, and I picked up the in-browser compiler from 
https://kovidgoyal.github.io/rapydscript/repl/rapydscript.js

Just for completeness I also tried building it on Windows from "node bin/web-repl-export" but got this error:

M:\HP_Cdrive\workspace>cd rapydscript-ng

M:\HP_Cdrive\workspace\rapydscript-ng>node bin/web-repl-export
M:\HP_Cdrive\workspace\rapydscript-ng\bin\web-repl-export:83
process.chdir(base_dir);
        ^

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at Object.<anonymous> (M:\HP_Cdrive\workspace\rapydscript-ng\bin\web-repl-export:83:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by kovidgoyal** [comment]
You need to pass the directory you want to export the web repl to, like this:

node bin/web-repl-export /path/to/somedir

and make sure it exists first
