### ISSUE TITLE
missing semicolons in output    --> nothing working at the momeht

### ISSUE THREAD

**Issue by JohnDenker** [kovidgoyal/rapydscript-ng#3]
#### Context
Consider the following trivial program:
````
bin/rapydscript --bare /dev/null | nodejs
```
#### Desired and Expected Behavior (normal python)
This works just fine under regular RapydScript

#### Observed Behavior (-ng fork)
```
bin/rapydscript --version
rapydscript-ng 0.4.0
bin/rapydscript --bare /dev/null | nodejs
[stdin]:1
self.stack=(new Error).stack};ValueError.prototype.name="ValueError"function _
                                                                    ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:73:16)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at Socket.<anonymous> (node.js:164:11)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

Note:  The same failure is observed with any program whatsoever AFAICT, independent of length.  Hacking a semicolon into the output in the obvious place just reveals more problems of the same ilk.

**Comment by kovidgoyal** [comment]
Use -p

bin/rapydscript --bare /dev/null -p | nodejs

I broke the uglifier a while ago, as I never use it myself. I have to get around to fixing it again.

**Comment by JohnDenker** [comment]
That was quick.  Thanks!
