### ISSUE TITLE
assignment of list slice with omitted 'stop' causes compiler crash

### ISSUE THREAD

**Issue by courtc** [kovidgoyal/rapydscript-ng#44]
test.pyj:
```python
data = [0,1,2,3,4]
data[-2:] = [10]
print(data)
```
```
$ python2.7 test.pyj && python3.5 test.pyj 
[0, 1, 2, 10]
[0, 1, 2, 10]
```
Here's what I get:
```
$ rapydscript test.pyj
release/compiler.js:13057
                    self.property2.print(output);
                                  ^

TypeError: Cannot read property 'print' of undefined
    at release/compiler.js:13057:35
    at OutputStream.with_square (release/compiler.js:11766:19)
    at release/compiler.js:13054:24
    at OutputStream.with_parens (release/compiler.js:11755:19)
    at print_splice_assignment (release/compiler.js:13051:20)
    at AST_Splice.ρσ_anonfunc [as print] (release/compiler.js:15057:25)
    at ρσ_anonfunc (release/compiler.js:15356:35)
    at AST_SimpleStatement.ρσ_anonfunc [as print] (release/compiler.js:15057:25)
    at display_body (release/compiler.js:12059:26)
    at release/compiler.js:14693:33
```
```
$ rapydscript --version
rapydscript-ng 0.7.10
```

**Comment by kovidgoyal** [comment]
Actually, splice assignment is currently completely broken. I'll fix it soonish.
