### ISSUE TITLE
format, count...are not functions 

### ISSUE THREAD

**Issue by artyprog** [kovidgoyal/rapydscript-ng#8]
Hello Kovid,

I experienced some problems with string methods.
Here is an example with the count, but it is the same with format
Can you help me ?

Regards

h-h-h".count();
---------- Running JavaScript ---------
TypeError: "h-h-h".count is not a function
    at <repl>:1:9
    at Object.exports.runInContext (vm.js:44:17)
    at runjs (/home/salvatore/applications/rapydscript/node_modules/rapydscript-ng/tools/repl.js:247:25)
    at compile_source (/home/salvatore/applications/rapydscript/node_modules/rapydscript-ng/tools/repl.js:285:9)
    at push (/home/salvatore/applications/rapydscript/node_modules/rapydscript-ng/tools/repl.js:296:26)
    at Interface.<anonymous> (/home/salvatore/applications/rapydscript/node_modules/rapydscript-ng/tools/repl.js:309:23)
    at emitOne (events.js:90:13)
    at Interface.emit (events.js:182:7)
    at Interface._onLine (readline.js:211:10)
    at Interface._line (readline.js:550:8)
>>>

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/rapydscript-ng#strings

**Comment by artyprog** [comment]
Thanks Kovid.

"g-h-i".split("-"); and it worked so I was confused.
Could you give me an example with 'format' and 'count'

**Comment by kovidgoyal** [comment]
split is a native JS function on the native JS string object. It does not behave like the python one, for string functions, always use str.function(string_object, ...)

str.format('{} {}', 1, 2)
str.count('aaa', 'a')

**Comment by artyprog** [comment]
Thank you very much Kovid.
Regards
